# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'designerXNkFcD.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QPushButton,
    QSizePolicy, QSpinBox, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(621, 730)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.ame_title = QLabel(self.centralwidget)
        self.ame_title.setObjectName(u"ame_title")
        self.ame_title.setGeometry(QRect(80, 50, 111, 31))
        font = QFont()
        font.setPointSize(14)
        self.ame_title.setFont(font)
        self.ame_title.setAlignment(Qt.AlignCenter)
        self.ame_image = QLabel(self.centralwidget)
        self.ame_image.setObjectName(u"ame_image")
        self.ame_image.setGeometry(QRect(80, 90, 101, 111))
        self.ame_image.setFont(font)
        self.ame_image.setPixmap(QPixmap(u"../../../../../../../../python_project/Day4/asset/americano.PNG"))
        self.ame_image.setAlignment(Qt.AlignCenter)
        self.ame_price = QLabel(self.centralwidget)
        self.ame_price.setObjectName(u"ame_price")
        self.ame_price.setGeometry(QRect(80, 210, 111, 31))
        self.ame_price.setFont(font)
        self.ame_price.setAlignment(Qt.AlignCenter)
        self.ame_ea = QLabel(self.centralwidget)
        self.ame_ea.setObjectName(u"ame_ea")
        self.ame_ea.setGeometry(QRect(70, 256, 61, 31))
        self.ame_ea.setFont(font)
        self.ame_ea.setAlignment(Qt.AlignCenter)
        self.ame_spin_box = QSpinBox(self.centralwidget)
        self.ame_spin_box.setObjectName(u"ame_spin_box")
        self.ame_spin_box.setGeometry(QRect(150, 260, 42, 22))
        self.late_spin_box = QSpinBox(self.centralwidget)
        self.late_spin_box.setObjectName(u"late_spin_box")
        self.late_spin_box.setGeometry(QRect(330, 264, 42, 22))
        self.late_price = QLabel(self.centralwidget)
        self.late_price.setObjectName(u"late_price")
        self.late_price.setGeometry(QRect(260, 214, 111, 31))
        self.late_price.setFont(font)
        self.late_price.setAlignment(Qt.AlignCenter)
        self.late_title = QLabel(self.centralwidget)
        self.late_title.setObjectName(u"late_title")
        self.late_title.setGeometry(QRect(260, 54, 111, 31))
        self.late_title.setFont(font)
        self.late_title.setAlignment(Qt.AlignCenter)
        self.late_image = QLabel(self.centralwidget)
        self.late_image.setObjectName(u"late_image")
        self.late_image.setGeometry(QRect(260, 94, 101, 111))
        self.late_image.setFont(font)
        self.late_image.setPixmap(QPixmap(u"../../../../../../../../python_project/Day4/asset/cafelate.PNG"))
        self.late_image.setAlignment(Qt.AlignCenter)
        self.late_ea = QLabel(self.centralwidget)
        self.late_ea.setObjectName(u"late_ea")
        self.late_ea.setGeometry(QRect(250, 260, 61, 31))
        self.late_ea.setFont(font)
        self.late_ea.setAlignment(Qt.AlignCenter)
        self.cio_ea = QLabel(self.centralwidget)
        self.cio_ea.setObjectName(u"cio_ea")
        self.cio_ea.setGeometry(QRect(420, 256, 61, 31))
        self.cio_ea.setFont(font)
        self.cio_ea.setAlignment(Qt.AlignCenter)
        self.cio_image = QLabel(self.centralwidget)
        self.cio_image.setObjectName(u"cio_image")
        self.cio_image.setGeometry(QRect(430, 90, 101, 111))
        self.cio_image.setFont(font)
        self.cio_image.setPixmap(QPixmap(u"../../../../../../../../python_project/Day4/asset/cio.PNG"))
        self.cio_image.setAlignment(Qt.AlignCenter)
        self.cio_spin_box = QSpinBox(self.centralwidget)
        self.cio_spin_box.setObjectName(u"cio_spin_box")
        self.cio_spin_box.setGeometry(QRect(500, 260, 42, 22))
        self.cio_title = QLabel(self.centralwidget)
        self.cio_title.setObjectName(u"cio_title")
        self.cio_title.setGeometry(QRect(430, 50, 111, 31))
        self.cio_title.setFont(font)
        self.cio_title.setAlignment(Qt.AlignCenter)
        self.cio_price = QLabel(self.centralwidget)
        self.cio_price.setObjectName(u"cio_price")
        self.cio_price.setGeometry(QRect(430, 210, 111, 31))
        self.cio_price.setFont(font)
        self.cio_price.setAlignment(Qt.AlignCenter)
        self.morning_ea = QLabel(self.centralwidget)
        self.morning_ea.setObjectName(u"morning_ea")
        self.morning_ea.setGeometry(QRect(70, 516, 61, 31))
        self.morning_ea.setFont(font)
        self.morning_ea.setAlignment(Qt.AlignCenter)
        self.morning_image = QLabel(self.centralwidget)
        self.morning_image.setObjectName(u"morning_image")
        self.morning_image.setGeometry(QRect(80, 350, 101, 111))
        self.morning_image.setFont(font)
        self.morning_image.setPixmap(QPixmap(u"../../../../../../../../python_project/Day4/asset/morning.PNG"))
        self.morning_image.setAlignment(Qt.AlignCenter)
        self.morning_spin_box = QSpinBox(self.centralwidget)
        self.morning_spin_box.setObjectName(u"morning_spin_box")
        self.morning_spin_box.setGeometry(QRect(150, 520, 42, 22))
        self.morning_title = QLabel(self.centralwidget)
        self.morning_title.setObjectName(u"morning_title")
        self.morning_title.setGeometry(QRect(80, 310, 111, 31))
        self.morning_title.setFont(font)
        self.morning_title.setAlignment(Qt.AlignCenter)
        self.morning_price = QLabel(self.centralwidget)
        self.morning_price.setObjectName(u"morning_price")
        self.morning_price.setGeometry(QRect(80, 470, 111, 31))
        self.morning_price.setFont(font)
        self.morning_price.setAlignment(Qt.AlignCenter)
        self.orange_ea = QLabel(self.centralwidget)
        self.orange_ea.setObjectName(u"orange_ea")
        self.orange_ea.setGeometry(QRect(250, 516, 61, 31))
        self.orange_ea.setFont(font)
        self.orange_ea.setAlignment(Qt.AlignCenter)
        self.orange_image = QLabel(self.centralwidget)
        self.orange_image.setObjectName(u"orange_image")
        self.orange_image.setGeometry(QRect(260, 350, 101, 111))
        self.orange_image.setFont(font)
        self.orange_image.setPixmap(QPixmap(u"../../../../../../../../python_project/Day4/asset/orange_juice.PNG"))
        self.orange_image.setAlignment(Qt.AlignCenter)
        self.orange_spin_box = QSpinBox(self.centralwidget)
        self.orange_spin_box.setObjectName(u"orange_spin_box")
        self.orange_spin_box.setGeometry(QRect(330, 520, 42, 22))
        self.orange_title = QLabel(self.centralwidget)
        self.orange_title.setObjectName(u"orange_title")
        self.orange_title.setGeometry(QRect(260, 310, 111, 31))
        self.orange_title.setFont(font)
        self.orange_title.setAlignment(Qt.AlignCenter)
        self.orange_price = QLabel(self.centralwidget)
        self.orange_price.setObjectName(u"orange_price")
        self.orange_price.setGeometry(QRect(260, 470, 111, 31))
        self.orange_price.setFont(font)
        self.orange_price.setAlignment(Qt.AlignCenter)
        self.apple_ea = QLabel(self.centralwidget)
        self.apple_ea.setObjectName(u"apple_ea")
        self.apple_ea.setGeometry(QRect(430, 516, 61, 31))
        self.apple_ea.setFont(font)
        self.apple_ea.setAlignment(Qt.AlignCenter)
        self.apple_image = QLabel(self.centralwidget)
        self.apple_image.setObjectName(u"apple_image")
        self.apple_image.setGeometry(QRect(440, 350, 101, 111))
        self.apple_image.setFont(font)
        self.apple_image.setPixmap(QPixmap(u"../../../../../../../../python_project/Day4/asset/apple_juice.PNG"))
        self.apple_image.setAlignment(Qt.AlignCenter)
        self.apple_spin_box = QSpinBox(self.centralwidget)
        self.apple_spin_box.setObjectName(u"apple_spin_box")
        self.apple_spin_box.setGeometry(QRect(510, 520, 42, 22))
        self.apple_title = QLabel(self.centralwidget)
        self.apple_title.setObjectName(u"apple_title")
        self.apple_title.setGeometry(QRect(440, 310, 111, 31))
        self.apple_title.setFont(font)
        self.apple_title.setAlignment(Qt.AlignCenter)
        self.apple_price = QLabel(self.centralwidget)
        self.apple_price.setObjectName(u"apple_price")
        self.apple_price.setGeometry(QRect(440, 470, 111, 31))
        self.apple_price.setFont(font)
        self.apple_price.setAlignment(Qt.AlignCenter)
        self.total_title = QLabel(self.centralwidget)
        self.total_title.setObjectName(u"total_title")
        self.total_title.setGeometry(QRect(50, 600, 111, 31))
        self.total_title.setFont(font)
        self.total_title.setAlignment(Qt.AlignCenter)
        self.total_price = QLabel(self.centralwidget)
        self.total_price.setObjectName(u"total_price")
        self.total_price.setGeometry(QRect(190, 600, 151, 31))
        self.total_price.setFont(font)
        self.total_price.setAlignment(Qt.AlignCenter)
        self.service_label = QLabel(self.centralwidget)
        self.service_label.setObjectName(u"service_label")
        self.service_label.setGeometry(QRect(60, 650, 251, 31))
        self.service_label.setFont(font)
        self.service_label.setAlignment(Qt.AlignCenter)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(360, 600, 191, 91))
        self.pushButton.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"kiosk", None))
        self.ame_title.setText(QCoreApplication.translate("MainWindow", u"\uc544\uba54\ub9ac\uce74\ub178", None))
        self.ame_image.setText("")
        self.ame_price.setText(QCoreApplication.translate("MainWindow", u"5000\uc6d0", None))
        self.ame_ea.setText(QCoreApplication.translate("MainWindow", u"\uc218\ub7c9", None))
        self.late_price.setText(QCoreApplication.translate("MainWindow", u"7000\uc6d0", None))
        self.late_title.setText(QCoreApplication.translate("MainWindow", u"\uce74\ud398\ub77c\ub5bc", None))
        self.late_image.setText("")
        self.late_ea.setText(QCoreApplication.translate("MainWindow", u"\uc218\ub7c9", None))
        self.cio_ea.setText(QCoreApplication.translate("MainWindow", u"\uc218\ub7c9", None))
        self.cio_image.setText("")
        self.cio_title.setText(QCoreApplication.translate("MainWindow", u"\uc18c\uae08\ube75", None))
        self.cio_price.setText(QCoreApplication.translate("MainWindow", u"2500\uc6d0", None))
        self.morning_ea.setText(QCoreApplication.translate("MainWindow", u"\uc218\ub7c9", None))
        self.morning_image.setText("")
        self.morning_title.setText(QCoreApplication.translate("MainWindow", u"\ubaa8\ub2dd\ube75", None))
        self.morning_price.setText(QCoreApplication.translate("MainWindow", u"4000\uc6d0", None))
        self.orange_ea.setText(QCoreApplication.translate("MainWindow", u"\uc218\ub7c9", None))
        self.orange_image.setText("")
        self.orange_title.setText(QCoreApplication.translate("MainWindow", u"\uc624\ub80c\uc9c0 \uc8fc\uc2a4", None))
        self.orange_price.setText(QCoreApplication.translate("MainWindow", u"4500\uc6d0", None))
        self.apple_ea.setText(QCoreApplication.translate("MainWindow", u"\uc218\ub7c9", None))
        self.apple_image.setText("")
        self.apple_title.setText(QCoreApplication.translate("MainWindow", u"\uc0ac\uacfc \uc8fc\uc2a4", None))
        self.apple_price.setText(QCoreApplication.translate("MainWindow", u"3000\uc6d0", None))
        self.total_title.setText(QCoreApplication.translate("MainWindow", u"\ucd1d \uc561", None))
        self.total_price.setText(QCoreApplication.translate("MainWindow", u"0 \uc6d0", None))
        self.service_label.setText("")
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\uc8fc\ubb38 \uc644\ub8cc", None))
    # retranslateUi

