# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'cafe_withpUVWff.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QPushButton,
    QSizePolicy, QSpinBox, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(627, 697)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.ame_title = QLabel(self.centralwidget)
        self.ame_title.setObjectName(u"ame_title")
        self.ame_title.setGeometry(QRect(80, 30, 138, 58))
        font = QFont()
        font.setPointSize(14)
        self.ame_title.setFont(font)
        self.ame_title.setAlignment(Qt.AlignCenter)
        self.ame_image = QLabel(self.centralwidget)
        self.ame_image.setObjectName(u"ame_image")
        self.ame_image.setGeometry(QRect(70, 70, 159, 159))
        self.ame_image.setFont(font)
        self.ame_image.setPixmap(QPixmap(u"../../../../../../../../../../../python_project/2023_11_03/asset/americano.png"))
        self.ame_image.setAlignment(Qt.AlignCenter)
        self.ame_price = QLabel(self.centralwidget)
        self.ame_price.setObjectName(u"ame_price")
        self.ame_price.setGeometry(QRect(110, 220, 100, 40))
        self.ame_price.setFont(font)
        self.ame_price.setAlignment(Qt.AlignCenter)
        self.ame_ea = QLabel(self.centralwidget)
        self.ame_ea.setObjectName(u"ame_ea")
        self.ame_ea.setGeometry(QRect(100, 250, 50, 40))
        self.ame_ea.setFont(font)
        self.ame_ea.setAlignment(Qt.AlignCenter)
        self.ame_spin_box = QSpinBox(self.centralwidget)
        self.ame_spin_box.setObjectName(u"ame_spin_box")
        self.ame_spin_box.setGeometry(QRect(170, 250, 50, 30))
        self.ame_spin_box.setFont(font)
        self.latte_spin_box = QSpinBox(self.centralwidget)
        self.latte_spin_box.setObjectName(u"latte_spin_box")
        self.latte_spin_box.setGeometry(QRect(320, 250, 50, 30))
        self.latte_spin_box.setFont(font)
        self.latte_image = QLabel(self.centralwidget)
        self.latte_image.setObjectName(u"latte_image")
        self.latte_image.setGeometry(QRect(220, 70, 159, 159))
        self.latte_image.setFont(font)
        self.latte_image.setPixmap(QPixmap(u"../../../../../../../../../../../python_project/2023_11_03/asset/cafelatte.png"))
        self.latte_image.setAlignment(Qt.AlignCenter)
        self.latte_title = QLabel(self.centralwidget)
        self.latte_title.setObjectName(u"latte_title")
        self.latte_title.setGeometry(QRect(230, 30, 138, 58))
        self.latte_title.setFont(font)
        self.latte_title.setAlignment(Qt.AlignCenter)
        self.latte_ea = QLabel(self.centralwidget)
        self.latte_ea.setObjectName(u"latte_ea")
        self.latte_ea.setGeometry(QRect(250, 250, 50, 40))
        self.latte_ea.setFont(font)
        self.latte_ea.setAlignment(Qt.AlignCenter)
        self.latte_price = QLabel(self.centralwidget)
        self.latte_price.setObjectName(u"latte_price")
        self.latte_price.setGeometry(QRect(260, 220, 100, 40))
        self.latte_price.setFont(font)
        self.latte_price.setAlignment(Qt.AlignCenter)
        self.salt_price = QLabel(self.centralwidget)
        self.salt_price.setObjectName(u"salt_price")
        self.salt_price.setGeometry(QRect(420, 220, 100, 40))
        self.salt_price.setFont(font)
        self.salt_price.setAlignment(Qt.AlignCenter)
        self.salt_ea = QLabel(self.centralwidget)
        self.salt_ea.setObjectName(u"salt_ea")
        self.salt_ea.setGeometry(QRect(410, 250, 50, 40))
        self.salt_ea.setFont(font)
        self.salt_ea.setAlignment(Qt.AlignCenter)
        self.salt_image = QLabel(self.centralwidget)
        self.salt_image.setObjectName(u"salt_image")
        self.salt_image.setGeometry(QRect(380, 70, 159, 159))
        self.salt_image.setFont(font)
        self.salt_image.setPixmap(QPixmap(u"../../../../../../../../../../../python_project/2023_11_03/asset/salt_bread.png"))
        self.salt_image.setAlignment(Qt.AlignCenter)
        self.salt_title = QLabel(self.centralwidget)
        self.salt_title.setObjectName(u"salt_title")
        self.salt_title.setGeometry(QRect(390, 30, 138, 58))
        self.salt_title.setFont(font)
        self.salt_title.setAlignment(Qt.AlignCenter)
        self.salt_spin_box = QSpinBox(self.centralwidget)
        self.salt_spin_box.setObjectName(u"salt_spin_box")
        self.salt_spin_box.setGeometry(QRect(480, 250, 50, 30))
        self.salt_spin_box.setFont(font)
        self.apple_spin_box = QSpinBox(self.centralwidget)
        self.apple_spin_box.setObjectName(u"apple_spin_box")
        self.apple_spin_box.setGeometry(QRect(490, 520, 50, 30))
        self.apple_spin_box.setFont(font)
        self.orange_ea = QLabel(self.centralwidget)
        self.orange_ea.setObjectName(u"orange_ea")
        self.orange_ea.setGeometry(QRect(260, 520, 50, 40))
        self.orange_ea.setFont(font)
        self.orange_ea.setAlignment(Qt.AlignCenter)
        self.apple_ea = QLabel(self.centralwidget)
        self.apple_ea.setObjectName(u"apple_ea")
        self.apple_ea.setGeometry(QRect(420, 520, 50, 40))
        self.apple_ea.setFont(font)
        self.apple_ea.setAlignment(Qt.AlignCenter)
        self.morning_image = QLabel(self.centralwidget)
        self.morning_image.setObjectName(u"morning_image")
        self.morning_image.setGeometry(QRect(80, 330, 159, 159))
        self.morning_image.setFont(font)
        self.morning_image.setPixmap(QPixmap(u"../../../../../../../../../../../python_project/2023_11_03/asset/morning_bread.png"))
        self.morning_image.setAlignment(Qt.AlignCenter)
        self.apple_price = QLabel(self.centralwidget)
        self.apple_price.setObjectName(u"apple_price")
        self.apple_price.setGeometry(QRect(430, 480, 100, 40))
        self.apple_price.setFont(font)
        self.apple_price.setAlignment(Qt.AlignCenter)
        self.morning_spin_box = QSpinBox(self.centralwidget)
        self.morning_spin_box.setObjectName(u"morning_spin_box")
        self.morning_spin_box.setGeometry(QRect(180, 520, 50, 30))
        self.morning_spin_box.setFont(font)
        self.orange_price = QLabel(self.centralwidget)
        self.orange_price.setObjectName(u"orange_price")
        self.orange_price.setGeometry(QRect(270, 480, 100, 40))
        self.orange_price.setFont(font)
        self.orange_price.setAlignment(Qt.AlignCenter)
        self.orange_image = QLabel(self.centralwidget)
        self.orange_image.setObjectName(u"orange_image")
        self.orange_image.setGeometry(QRect(230, 330, 159, 159))
        self.orange_image.setFont(font)
        self.orange_image.setPixmap(QPixmap(u"../../../../../../../../../../../python_project/2023_11_03/asset/orange_juice.png"))
        self.orange_image.setAlignment(Qt.AlignCenter)
        self.orange_title = QLabel(self.centralwidget)
        self.orange_title.setObjectName(u"orange_title")
        self.orange_title.setGeometry(QRect(240, 290, 138, 58))
        self.orange_title.setFont(font)
        self.orange_title.setAlignment(Qt.AlignCenter)
        self.apple_title = QLabel(self.centralwidget)
        self.apple_title.setObjectName(u"apple_title")
        self.apple_title.setGeometry(QRect(400, 290, 138, 58))
        self.apple_title.setFont(font)
        self.apple_title.setAlignment(Qt.AlignCenter)
        self.morning_title = QLabel(self.centralwidget)
        self.morning_title.setObjectName(u"morning_title")
        self.morning_title.setGeometry(QRect(90, 290, 138, 58))
        self.morning_title.setFont(font)
        self.morning_title.setAlignment(Qt.AlignCenter)
        self.apple_image = QLabel(self.centralwidget)
        self.apple_image.setObjectName(u"apple_image")
        self.apple_image.setGeometry(QRect(390, 330, 159, 159))
        self.apple_image.setFont(font)
        self.apple_image.setPixmap(QPixmap(u"../../../../../../../../../../../python_project/2023_11_03/asset/apple_juice.png"))
        self.apple_image.setAlignment(Qt.AlignCenter)
        self.morning_ea = QLabel(self.centralwidget)
        self.morning_ea.setObjectName(u"morning_ea")
        self.morning_ea.setGeometry(QRect(110, 520, 50, 40))
        self.morning_ea.setFont(font)
        self.morning_ea.setAlignment(Qt.AlignCenter)
        self.morning_price = QLabel(self.centralwidget)
        self.morning_price.setObjectName(u"morning_price")
        self.morning_price.setGeometry(QRect(120, 480, 100, 40))
        self.morning_price.setFont(font)
        self.morning_price.setAlignment(Qt.AlignCenter)
        self.orange_spin_box = QSpinBox(self.centralwidget)
        self.orange_spin_box.setObjectName(u"orange_spin_box")
        self.orange_spin_box.setGeometry(QRect(330, 520, 50, 30))
        self.orange_spin_box.setFont(font)
        self.total_title = QLabel(self.centralwidget)
        self.total_title.setObjectName(u"total_title")
        self.total_title.setGeometry(QRect(90, 590, 138, 48))
        self.total_title.setFont(font)
        self.total_title.setAlignment(Qt.AlignCenter)
        self.total_price = QLabel(self.centralwidget)
        self.total_price.setObjectName(u"total_price")
        self.total_price.setGeometry(QRect(230, 590, 138, 48))
        self.total_price.setFont(font)
        self.total_price.setAlignment(Qt.AlignCenter)
        self.push_button = QPushButton(self.centralwidget)
        self.push_button.setObjectName(u"push_button")
        self.push_button.setGeometry(QRect(400, 590, 130, 50))
        self.push_button.setFont(font)
        self.service_label = QLabel(self.centralwidget)
        self.service_label.setObjectName(u"service_label")
        self.service_label.setGeometry(QRect(110, 620, 251, 48))
        self.service_label.setFont(font)
        self.service_label.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"kiosk", None))
        self.ame_title.setText(QCoreApplication.translate("MainWindow", u"\uc544\uba54\ub9ac\uce74\ub178", None))
        self.ame_image.setText("")
        self.ame_price.setText(QCoreApplication.translate("MainWindow", u"5000\uc6d0", None))
        self.ame_ea.setText(QCoreApplication.translate("MainWindow", u"\uc218\ub7c9", None))
        self.latte_image.setText("")
        self.latte_title.setText(QCoreApplication.translate("MainWindow", u"\uce74\ud398\ub77c\ub5bc", None))
        self.latte_ea.setText(QCoreApplication.translate("MainWindow", u"\uc218\ub7c9", None))
        self.latte_price.setText(QCoreApplication.translate("MainWindow", u"7000\uc6d0", None))
        self.salt_price.setText(QCoreApplication.translate("MainWindow", u"2500\uc6d0", None))
        self.salt_ea.setText(QCoreApplication.translate("MainWindow", u"\uc218\ub7c9", None))
        self.salt_image.setText("")
        self.salt_title.setText(QCoreApplication.translate("MainWindow", u"\uc18c\uae08\ube75", None))
        self.orange_ea.setText(QCoreApplication.translate("MainWindow", u"\uc218\ub7c9", None))
        self.apple_ea.setText(QCoreApplication.translate("MainWindow", u"\uc218\ub7c9", None))
        self.morning_image.setText("")
        self.apple_price.setText(QCoreApplication.translate("MainWindow", u"3000\uc6d0", None))
        self.orange_price.setText(QCoreApplication.translate("MainWindow", u"4500\uc6d0", None))
        self.orange_image.setText("")
        self.orange_title.setText(QCoreApplication.translate("MainWindow", u"\uc624\ub80c\uc9c0 \uc8fc\uc2a4", None))
        self.apple_title.setText(QCoreApplication.translate("MainWindow", u"\uc0ac\uacfc \uc8fc\uc2a4", None))
        self.morning_title.setText(QCoreApplication.translate("MainWindow", u"\ubaa8\ub2dd\ube75", None))
        self.apple_image.setText("")
        self.morning_ea.setText(QCoreApplication.translate("MainWindow", u"\uc218\ub7c9", None))
        self.morning_price.setText(QCoreApplication.translate("MainWindow", u"4000\uc6d0", None))
        self.total_title.setText(QCoreApplication.translate("MainWindow", u"\ucd1d \uc561", None))
        self.total_price.setText(QCoreApplication.translate("MainWindow", u"0 \uc6d0", None))
        self.push_button.setText(QCoreApplication.translate("MainWindow", u"\uc8fc\ubb38 \uc644\ub8cc", None))
        self.service_label.setText("")
    # retranslateUi